stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "start building ..."
    - cd /home/www/
    - ./docker_build tilitili-bot springboot master
  only:
    - master

deploy:
  stage: deploy
  script:
    - echo "start deploy ..."
    - cd /home/www/
    - ./docker_deploy_test tilitili-bot 43.142.163.203 8087 172.27.0.7
  only:
    - master