stages:
  - build
  - deploy

bulid:
  stage: build
  script:
    - echo "start building ..."
    - cd /home/www/
    - ./docker_build tilitili-bot springboot master
  only:
    - master

deploy:
  stage: deploy
  script:
    - echo "start deploy ..."
    - cd /home/www/
    - ./docker_deploy tilitili-bot 43.142.163.203 8087 10.0.0.17
  only:
    - master