From docker.tilitili.club/tilitili/tilitili-java:8-zh-jre

ADD target/*.jar tilitili-bot.jar

ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=pro -Xmx250M -Xms250M -Duser.timezone=GMT+8", "tilitili-bot.jar"]